name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: ["1.21"]
        rust:
          - version: stable
            clippy: true
          - version: 1.81.0 # As specified in rust-toolchain
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: ${{ matrix.go }}

    - name: Install Rust toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: ${{ matrix.rust.version }}
        override: true
        profile: minimal

    - name: Build
      run: make all

    - name: Install Linters
      run: go install github.com/golangci/golangci-lint/v2/cmd/golangci-lint@v2.4.0

    - name: Test
      run: make test
